services:
    locator_location.twig.extension:
        class: Locator\LocationBundle\Twig\Extensions\LocatorLocationExtension
        tags:
            - { name: twig.extension }
    ajax_response:
        class: Locator\LocationBundle\Utilities\AjaxResponse
        arguments: [@lexik_translation.translator]
    form_errors:
        class: Locator\LocationBundle\Utilities\FormErrors
